{% set name = "perl-log-log4perl" %}
{% set version = "1.57" %}
{% set sha256 = "0f8fcb7638a8f3db4c797df94fdbc56013749142f2f94cbc95b43c9fca096a13" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETJ/Log-Log4perl-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-file-path
    - perl-dbi
  run:
    - perl
    - perl-file-path
    - perl-dbi

test:
  imports:
    - Log::Log4perl
    - Log::Log4perl::Config
    - Log::Log4perl::Level
    - Log::Log4perl::Logger
  commands:
    - l4p-tmpl

about:
  home: https://metacpan.org/dist/Log-Log4perl
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: Log4j implementation for Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
    - LICENSE

extra:
  recipe-maintainers:
    - cbrueffer
